approval_policy = "never"
model_reasoning_effort = "high"
sandbox_mode = "danger-full-access"
model = "gpt-5"

[tools]
web_search = true

[projects."/home/leoc"]
trust_level = "trusted"

[projects."/home/leoc/projects/leo91000/eliah"]
trust_level = "trusted"

[projects."/home/leoc/projects/weweb/weweb-assets/ww-input-otp"]
trust_level = "trusted"

[projects."/home/leoc/projects/weweb/weweb-assets/ww-chat"]
trust_level = "trusted"

[projects."/home/leoc/projects/weweb/weweb-plugin-figma"]
trust_level = "trusted"

[projects."/home/leoc/projects/weweb/weweb-editor"]
trust_level = "trusted"

[projects."/home/leoc/projects/leo91000/vue-tiptap-renderer"]
trust_level = "trusted"

[projects."/home/leoc/projects/weweb"]
trust_level = "trusted"

[projects."/home/leoc/projects/weweb/weweb-assets/ww-chat-ai"]
trust_level = "trusted"

[projects."/home/leoc/projects/weweb/weweb-assets"]
trust_level = "trusted"

[mcp_servers.browsermcp]
command = "npx"
args = ["@browsermcp/mcp@latest"]
