wallpaper {
    monitor = eDP-2
    path = /home/leoc/.config/wallpapers/pywallpaper.jpg
    fit_mode = cover
}

wallpaper {
    monitor =
    path = /home/leoc/.config/wallpapers/pywallpaper.jpg
    fit_mode = cover
}

splash = false
