[Service]
Environment=QT_QUICK_CONTROLS_STYLE=Material
Environment=QT_QUICK_CONTROLS_MATERIAL_THEME=Dark
Environment=QT_QUICK_CONTROLS_MATERIAL_FOREGROUND=#FFFFFF
Environment=QT_QUICK_CONTROLS_MATERIAL_BACKGROUND=#1E1E2E
